/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAiInsightsRouteImport } from './routes/_app.ai-insights'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAutomationRouteImport } from './routes/_app.automation'
import { Route as AppBuildingsRouteImport } from './routes/_app.buildings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEnergyRouteImport } from './routes/_app.energy'
import { Route as AppFloorsRouteImport } from './routes/_app.floors'
import { Route as AppLightingRouteImport } from './routes/_app.lighting'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppZonesRouteImport } from './routes/_app.zones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildingsRoute = AppBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEnergyRoute = AppEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => AppRoute,
} as any)
const AppFloorsRoute = AppFloorsRouteImport.update({
  id: '/floors',
  path: '/floors',
  getParentRoute: () => AppRoute,
} as any)
const AppLightingRoute = AppLightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppZonesRoute = AppZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/alerts': typeof AppAlertsRoute
  '/automation': typeof AppAutomationRoute
  '/buildings': typeof AppBuildingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/energy': typeof AppEnergyRoute
  '/floors': typeof AppFloorsRoute
  '/lighting': typeof AppLightingRoute
  '/reports': typeof AppReportsRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/zones': typeof AppZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/alerts': typeof AppAlertsRoute
  '/automation': typeof AppAutomationRoute
  '/buildings': typeof AppBuildingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/energy': typeof AppEnergyRoute
  '/floors': typeof AppFloorsRoute
  '/lighting': typeof AppLightingRoute
  '/reports': typeof AppReportsRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/zones': typeof AppZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-insights': typeof AppAiInsightsRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/buildings': typeof AppBuildingsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/energy': typeof AppEnergyRoute
  '/_app/floors': typeof AppFloorsRoute
  '/_app/lighting': typeof AppLightingRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/zones': typeof AppZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-insights'
    | '/alerts'
    | '/automation'
    | '/buildings'
    | '/dashboard'
    | '/energy'
    | '/floors'
    | '/lighting'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/users'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-insights'
    | '/alerts'
    | '/automation'
    | '/buildings'
    | '/dashboard'
    | '/energy'
    | '/floors'
    | '/lighting'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/users'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai-insights'
    | '/_app/alerts'
    | '/_app/automation'
    | '/_app/buildings'
    | '/_app/dashboard'
    | '/_app/energy'
    | '/_app/floors'
    | '/_app/lighting'
    | '/_app/reports'
    | '/_app/rooms'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai-insights': {
      id: '/_app/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buildings': {
      id: '/_app/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AppBuildingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/energy': {
      id: '/_app/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof AppEnergyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/floors': {
      id: '/_app/floors'
      path: '/floors'
      fullPath: '/floors'
      preLoaderRoute: typeof AppFloorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lighting': {
      id: '/_app/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof AppLightingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/zones': {
      id: '/_app/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AppZonesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppBuildingsRoute: typeof AppBuildingsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEnergyRoute: typeof AppEnergyRoute
  AppFloorsRoute: typeof AppFloorsRoute
  AppLightingRoute: typeof AppLightingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppZonesRoute: typeof AppZonesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppBuildingsRoute: AppBuildingsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEnergyRoute: AppEnergyRoute,
  AppFloorsRoute: AppFloorsRoute,
  AppLightingRoute: AppLightingRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppZonesRoute: AppZonesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
